# name: test

# shape_meta: &shape_meta
#   # acceptable types: rgb, low_dim
#   obs:
#     agentview_image:
#       shape: [3, 240, 320]
#       type: rgb
#     agent_pos:
#       shape: [14]
#       type: low_dim
#   action: 
#     shape: [14]

# task_name: &task_name square
# dataset_type: &dataset_type ph
# dataset_path: &dataset_path data/robomimic/datasets/${task.task_name}/${task.dataset_type}/image_abs.hdf5
# abs_action: &abs_action True

# env_runner:
#   _target_: diffusion_policy.env_runner.robomimic_image_runner.RobomimicImageRunner
#   dataset_path: *dataset_path
#   shape_meta: *shape_meta
#   # costs 1GB per env
#   n_train: 6
#   n_train_vis: 2
#   train_start_idx: 0
#   n_test: 50
#   n_test_vis: 4
#   test_start_seed: 100000
#   # use python's eval function as resolver, single-quoted string as argument
#   max_steps: ${eval:'500 if "${task.dataset_type}" == "mh" else 400'}
#   n_obs_steps: ${n_obs_steps}
#   n_action_steps: ${n_action_steps}
#   render_obs_key: 'agentview_image'
#   fps: 10
#   crf: 22
#   past_action: ${past_action_visible}
#   abs_action: *abs_action
#   tqdm_interval_sec: 1.0
#   n_envs: 28
# # evaluation at this config requires a 16 core 64GB instance.

# dataset:
#   _target_: diffusion_policy.dataset.robot_image_dataset.RobotImageDataset
#   shape_meta: *shape_meta
#   dataset_path: *dataset_path
#   horizon: ${horizon}
#   pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
#   pad_after: ${eval:'${n_action_steps}-1'}
#   n_obs_steps: ${dataset_obs_steps}
#   abs_action: *abs_action
#   rotation_rep: 'rotation_6d'
#   use_legacy_normalizer: False
#   use_cache: True
#   seed: 42
#   val_ratio: 0.02

name: block_sweep

image_shape: &image_shape [3, 128, 128]
shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    image:
      shape: *image_shape
      type: rgb
    agent_pos:
      shape: [14]
      type: low_dim
  action:
    shape: [14]

env_runner:
  _target_: diffusion_policy.env_runner.pusht_image_runner.PushTImageRunner
  n_train: 6
  n_train_vis: 2
  train_start_seed: 0
  n_test: 50
  n_test_vis: 4
  legacy_test: True
  test_start_seed: 100000
  max_steps: 300
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 10
  past_action: ${past_action_visible}
  n_envs: null

dataset:
  _target_: diffusion_policy.dataset.robot_image_dataset.RobotImageDataset
  zarr_path: data/block_sweep_20.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
